fix coding style

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -2,6 +2,7 @@ name: chocolatine
 
 env:
     MIRROR_URL: git@github.com:EpitechPromo2028/B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet.git
+    EXECUTABLES: chocolatine
 
 on:
     push:
@@ -14,14 +15,22 @@ on:
 jobs:
     # Checks for coding-style errors.
     check_coding_style:
-        if: ${{ github.github.repository != 'B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet' }}
+        if: ${{ github.repository != 'B-DOP-200-NCY-2-1-chocolatine-*' }}
         runs-on: ubuntu-latest
         container: ghcr.io/epitech/coding-style-checker:latest
 
         steps:
+            - name: Checking repositoty
+              uses: actions/checkout@v4
+              with:
+                repository: ''
             - name: Runs coding-style report
               run: |
                 check.sh . .
+                while IFS= read -r -a line; do
+                    fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
+                    echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
+                done < coding-style-reports.log
                 if [ -z coding-style-reports.log ]; then
                     exit 1
                 fi
@@ -29,34 +38,50 @@ jobs:
 
     # Checks that project actually compiles
     check_program_compilation:
-        if: ${{ github.github.repository != 'B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet' }}
+        if: ${{ github.repository != 'B-DOP-200-NCY-2-1-chocolatine-*' }}
         runs-on: ubuntu-latest
         container: epitechcontent/epitest-docker
         needs: check_coding_style
+        timeout-minutes: 2
 
         steps:
+            - name: Checking repositoty
+              uses: actions/checkout@v4
+              with:
+                repository: ''
             - name: Builds project
               run: |
-                make && make re && make clean && make re
-                if [ $? -ne 0 ]; then
-                    exit 1
-                fi
+                make
+            - name: Clean project
+              run: |
+                make clean
+            - name: Checking permissions
+              run: |
+                for executables in $EXECUTABLES; do
+                    if [ ! - x ]; then
+                        exit 1
+                    fi
+                done
 
     # Launches unit tests
     run_tests:
-        if: ${{ github.github.repository != 'B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet' }}
+        if: ${{ github.repository != 'B-DOP-200-NCY-2-1-chocolatine-*' }}
         runs-on: ubuntu-latest
         container: epitechcontent/epitest-docker
         needs: check_program_compilation
 
         steps:
+          - name: Checking repositoty
+            uses: actions/checkout@v4
+            with:
+              repository: ''
           - name: Running unit tests
             run: |
               make tests_run
 
     # Redirects to Epitech's repository.
     push_to_mirror:
-        if: ${{ github.github.repository != 'B-DOP-200-NCY-2-1-chocolatine-laszlo.serdet' }}
+        if: ${{ github.repository != 'B-DOP-200-NCY-2-1-chocolatine-*' }}
         runs-on: ubuntu-latest
         container: epitechcontent/epitest-docker
         needs: run_tests
